name: "CI"
on:
  push:
    branch: [master]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 2,5' # every Tuesday & Friday
permissions: write-all
jobs:
  lockfile:
    runs-on: [ubuntu-latest]
    if: ${{ github.event_name != 'pull_request' && github.ref_name != 'nightly-update' && (github.event.head_commit.author.name == 'fmway' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') }}
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        extra-conf: experimental-features = nix-command flakes auto-allocate-uids configurable-impure-env
    - uses: DeterminateSystems/update-flake-lock@v24
      name: Update flake.lock
      with:
        branch: nightly-update
        token: ${{ secrets.GITHUB_TOKEN }}
        git-author-name: 'little fmway'
        git-author-email: 'fm18lv@gmail.com'
        git-committer-name: 'little fmway'
        git-committer-email: 'fm18lv@gmail.com'
        commit-msg: 'chore(lockfile): update flake.lock'
        pr-title: 'chore(lockfile): update flake.lock'
        pr-labels: |
          dependencies
          automated
